name: Rakurai Scheduler Binary Attestation

on:
    push:
        tags:
            - "*"

env:
  CARGO_TERM_COLOR: always

permissions:
  id-token: write
  contents: read
  attestations: write

jobs:
    build:
        strategy:
          matrix:
            os: [ubuntu-22.04, ubuntu-24.04]

        runs-on: ${{ matrix.os }}

        steps:
        - uses: actions/checkout@v4
          with:
            submodules: true 
      
        - name: Clone Scheduler Private Repository
          uses: actions/checkout@v4
          with:
            repository: rakurai-io/scheduler_1_0
            ref: ${{ github.ref_name }}
            token: ${{ secrets.RAKURAI_SCHEDULER }}
            path: core/src/banking_stage/rakurai_scheduler
            submodules: true

        - name: Install Dependencies
          run: |
            rustup update
            sudo apt-get update
            sudo apt-get install libssl-dev libudev-dev pkg-config zlib1g-dev llvm clang cmake make libprotobuf-dev protobuf-compiler libclang-dev

        - name: Build Scheduler Library
          run: |
            git apply core/src/banking_stage/rakurai_scheduler/lib_building.patch
            cargo build --release -p rakurai-scheduler

        - name: Generate artifact attestation
          uses: actions/attest-build-provenance@v3
          with:
            subject-path: 'target/release/librakurai_scheduler_1_0.so'

        - name: Get branch name for tagged commit
          id: branch_name
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
            BRANCH_NAME=$(gh api repos/${{ github.repository }}/commits/${{ github.sha }}/branches-where-head --jq '.[0].name' || echo "unknown")
            echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT
            echo "Branch name is $BRANCH_NAME"

        - name: Create tar of scheduler library
          run: |
            TAR_NAME="${{ steps.branch_name.outputs.branch_name }}_${{ matrix.os }}.tar.gz"
            tar -cvzf $TAR_NAME target/release/librakurai_scheduler_1_0.so

        - name: Copy binary to Backend
          env:
            BACKEND_SSH_KEY: ${{ secrets.BACKEND_SSH_KEY }}
            BACKEND_IP: ${{ secrets.BACKEND_IP }}
            BACKEND_USER: ${{ secrets.BACKEND_USER }}
            BACKEND_PATH: ${{ secrets.BACKEND_PATH }}

          run: |
            echo "$BACKEND_SSH_KEY" > backend_key.pem
            chmod 600 backend_key.pem

            TAR_NAME="${{ steps.branch_name.outputs.branch_name }}_${{ matrix.os }}.tar.gz"
            scp -o StrictHostKeyChecking=no -i backend_key.pem \
              $TAR_NAME \
              ${BACKEND_USER}@${BACKEND_IP}:${BACKEND_PATH}/

            shred -u backend_key.pem